org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G

# Mod info
mod_id=originsx
mod_name=OriginsX
mod_version=2.0.0
mod_description=A beautiful, extensible race selection mod built on Race API
mod_license=MIT
mod_url=

# Minecraft
minecraft_version=26.2
minecraft_version_range=[26.2]
loader_version=4
neo_version=26.2.0.67
ldlib2_version=26.2.2.35
raceapi_version=2.0.0
