org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G

# Mod info
mod_id=originsx_skilltree
mod_name=OriginsX - Skill Tree
mod_version=1.4.11
mod_description=Progressive skill trees for OriginsX races: unlock and upgrade race powers with skill shards
mod_license=MIT
mod_url=

# Minecraft
minecraft_version=26.2
minecraft_version_range=[26.2]
loader_version=4
neo_version=26.2.0.67
ldlib2_version=26.2.2.35
raceapi_version=0.5.0
